### ISSUE TITLE
Cannot read property fluid of null

### ISSUE THREAD

**Issue by twhite96** [LekoArts/gatsby-starter-portfolio-jodie#58]
I deployed this to Netlify a couple days ago, edited it, everything was copacetic. Add images today, add the appropriate new cover to the project, and...I get this error: `TypeError: cannot read property fluid of 'null'`. I have optimized the images, renamed them, deleted them put them back, deleted and put back images in other projects, deleted the cache folder, reinstalled node modules, updated node modules, etc. Nothing has worked. I've hard reloaded the browser when running the dev server, nada.

The problem is in the file `templates/projects.tsx` on lines 114 and 118. I modified the file, just deleting the contact us button. I put it back, etc, but still getting the error. Here is the code in that file:

```js
import React from 'react'
import { graphql } from 'gatsby'
import Img from 'gatsby-image'
import { transparentize, readableColor } from 'polished'
import styled from 'styled-components'
import { config, useSpring, animated } from 'react-spring'
import Layout from '../components/layout'
import { Box, AnimatedBox } from '../elements'
import SEO from '../components/SEO'


const PBox = styled(AnimatedBox)`
  max-width: 1400px;
  margin: 0 auto;
`

const Content = styled(Box)<{ bg: string }>`
  background-color: ${props => transparentize(0.9, props.bg)};

  .gatsby-image-wrapper:not(:last-child) {
    margin-bottom: ${props => props.theme.space[10]};

    @media (max-width: ${props => props.theme.breakpoints[3]}) {
      margin-bottom: ${props => props.theme.space[8]};
    }
  }
`

const Category = styled(AnimatedBox)`
  letter-spacing: 0.05em;
  font-size: ${props => props.theme.fontSizes[1]};
  text-transform: uppercase;
`

const Description = styled(animated.div)`
  max-width: 960px;
  letter-spacing: -0.003em;
  --baseline-multiplier: 0.179;
  --x-height-multiplier: 0.35;
  line-height: 1.58;
`

type PageProps = {
  data: {
    project: {
      title_detail: string
      color: string
      category: string
      desc: string
      slug: string
      parent: {
        modifiedTime: string
        birthTime: string
      }
      cover: {
        childImageSharp: {
          resize: {
            src: string
          }
        }
      }
    }
    images: {
      edges: {
        node: {
          name: string
          childImageSharp: {
            fluid: {
              aspectRatio: number
              src: string
              srcSet: string
              sizes: string
              base64: string
              tracedSVG: string
              srcWebp: string
              srcSetWebp: string
            }
          }
        }
      }[]
    }
  }
}

const Project: React.FunctionComponent<PageProps> = ({ data: { project, images } }) => {
  const categoryAnimation = useSpring({
    config: config.slow,
    from: { opacity: 0, transform: 'translate3d(0, -30px, 0)' },
    to: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
  })

  const titleAnimation = useSpring({ config: config.slow, delay: 300, from: { opacity: 0 }, to: { opacity: 1 } })
  const descAnimation = useSpring({ config: config.slow, delay: 600, from: { opacity: 0 }, to: { opacity: 1 } })
  const imagesAnimation = useSpring({ config: config.slow, delay: 800, from: { opacity: 0 }, to: { opacity: 1 } })

  return (
    <Layout color={project.color}>
      <SEO
        pathname={project.slug}
        title={`${project.title_detail} | Jodie`}
        desc={project.desc}
        node={project.parent}
        banner={project.cover.childImageSharp.resize.src}
        individual
      />
      <PBox py={10} px={[6, 6, 8, 10]}>
        <Category style={categoryAnimation}>{project.category}</Category>
        <animated.h1 style={titleAnimation}>{project.title_detail}</animated.h1>
        <Description style={descAnimation}>
          <div dangerouslySetInnerHTML={{ __html: project.desc }} />
        </Description>
      </PBox>
      <Content bg={project.color} py={10}>
        <PBox style={imagesAnimation} px={[6, 6, 8, 10]}>
          {images.edges.map(image => (
            <Img
              alt={image.node.name}
              key={image.node.childImageSharp.fluid.src}
              fluid={image.node.childImageSharp.fluid}
            />
          ))}
        </PBox>
      </Content>
    </Layout>
  )
}

export default Project

export const query = graphql`
  query ProjectTemplate($slug: String!, $images: String!) {
    project: projectsYaml(slug: { eq: $slug }) {
      title_detail
      color
      category
      desc
      slug
      parent {
        ... on File {
          modifiedTime
          birthTime
        }
      }
      cover {
        childImageSharp {
          resize(width: 1200, height: 675, quality: 80) {
            src
          }
        }
      }
    }
    images: allFile(filter: { relativePath: { regex: $images } }) {
      edges {
        node {
          name
          childImageSharp {
            fluid(quality: 95, maxWidth: 1200) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    }
  }
`
```

The lines in question:

```jsx
<PBox style={imagesAnimation} px={[6, 6, 8, 10]}>
          {images.edges.map(image => (
            <Img
              alt={image.node.name}
              key={image.node.childImageSharp.fluid.src}
              fluid={image.node.childImageSharp.fluid}
            />
          ))}
</PBox>
```

Thanks for your help.

**Comment by twhite96** [comment]
Here is my projects file:

```yaml
- title: "iPhoneography"
  title_detail: "iPhone photos, street, tones, etc."
  slug: "iphone-shots"
  category: "Street Art"
  color: "white"
  images: "color"
  cover: "./iPhoneography/iphones1.jpg"
  desc: "The iPhone was first introduced in June 2007. It was groundbreaking, however the camera was lacking. In 2011, the iPhone 4s was released, changing the mobile photography game forever with its 8MP camera. This let the iOS App Store thrive with an abundance of photo and video editing apps, more so than any other app store (still). Currently, the iPhone Xs line of cameras have 12MP, two lenses, one telephoto and one wide; it can also record slow-motion video up to 120 fps and 4K video up to 60 fps."

- title: "Mobitog Project 52, 2019"
  title_detail: "Shooting every week is hard. Can you do it?"
  slug: "mobitog-52-2019"
  category: "Mobitog"
  color: "#90BDDF"
  images: "projects"
  cover: "./mobitog-project-52-2019/1-mobitog-52.jpg"
  desc: "Neon gives a distinct reddish-orange glow when used in low-voltage neon glow lamps, high-voltage discharge tubes and neon advertising signs. The red emission line from neon also causes the well known red light of helium–neon lasers. Neon is used in some plasma tube and refrigerant applications but has few other commercial uses. It is commercially extracted by the fractional distillation of liquid air. Since air is the only source, it is considerably more expensive than helium."

- title: "Black & White"
  title_detail: "Black & White"
  slug: "black-and-white"
  category: "Still"
  color: "white"
  images: "bw"
  cover: "./bw/projects-bw-001.jpg"
  desc: "Monochrome photography is photography where each position on an image can record and show a different amount of light, but not a different hue. It includes all forms of black-and-white photography, which produce images containing tones of neutral grey ranging from black to white."

- title: "Street"
  title_detail: "Street photograph is important but that's not why I like to shoot it."
  slug: "street"
  category: "Street Photography"
  color: "#ae81ff"
  images: "street"
  cover: "./street-photography/2019-04-29-9.jpg"
  desc: "Diane Arbus, Vivian Maier, Henri Cartier-Bresson. These are some of the greatest street photographers of all time. What makes them, and street photography so special? Chance."

- title: "Products"
  title_detail: "Every now and again, product shots are necessary."
  slug: "products"
  category: "Product Shots"
  color: "#06d7d9"
  images: "products"
  cover: "./products/2019-04-29-15-min.jpg"
  desc: "Sometimes I take shots of products for my developer Instagram account. These are those photos."

- title: "Nature"
  title_detail: "Colors everywhere."
  slug: "nature"
  category: "Nature"
  color: "#ffc600"
  images: "nature"
  cover: "./nature/2019-04-29-5-min.jpg"
  desc: "Nature, whether flowers, beaches, or just sunlight, can have amazing effects on your mood. Getting out and shooting is something I have made a priority."

- title: "Architecture"
  title_detail: "Cityscapes and buildings are some of my favorite things to shoot."
  slug: "architecture"
  category: "Architecture"
  color: "#282c35"
  images: "architecture"
  cover: "./architecture/2019-04-29-39.jpg"
  desc: "There are buildings and cityscapes here from Pittsburgh and Central Pa. Mostly taken with the iPhone, and soon the Canon M100."

- title: "Tones"
  title_detail: "A few different shades of life in the city."
  slug: "tones"
  category: "Tones"
  color: "#269358"
  images: "tones"
  cover: "./tones/2019-04-29-8.jpg"
  desc: "Getting tones, seeing them correctly, and making them pop, is an art all unto itself."

- title: "Abstract & Art"
  title_detail: "Something quirky."
  slug: "art"
  category: "Art"
  color: "#d72323"
  images: "tones"
  cover: "./art/2019-04-29-20.jpg"
  desc: "For things that defy logic but engage the senses."
```
